# Generated by Django 2.0.2 on 2018-02-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='제조사명'),
            preserve_default=False,
        ),
    ]
