# Generated by Django 2.0.2 on 2018-02-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_inheritance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='multiple_inheritance.Article')),
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multiple_inheritance.Book')),
            ],
            bases=('multiple_inheritance.book', 'multiple_inheritance.article'),
        ),
        migrations.RemoveField(
            model_name='bookrevidew',
            name='article_ptr',
        ),
        migrations.RemoveField(
            model_name='bookrevidew',
            name='book_ptr',
        ),
        migrations.DeleteModel(
            name='BookRevidew',
        ),
    ]
